export const APP_LOAD = 'APP_LOAD'
export const USER_LOGGED_IN = 'USER_LOGGED_IN'


export const REQUEST_FETCHING = 'REQUEST_FETCHING';
export const REQUEST_FETCHED = 'REQUEST_FETCHED';
export const USER_LOADED = 'USER_LOADED'
export const LOAD_USER = 'LOAD_USER'
export const USER_LOGGING_IN = 'USER_LOGGING_IN'
export const USER_LOGIN_FAILED = 'USER_LOGIN_FAILED'
export const USER_REGISTERING = 'USER_REGISTERING'
export const USER_REGISTERED = 'USER_REGISTERED'
export const USER_REGISTERING_FAILED = 'USER_REGISTERING_FAILED'
export const ERROR_MESSAGE_CLEARED = 'ERROR_MESSAGE_CLEARED'
export const WALLET_LOADED = 'WALLET_LOADED'
export const WALLET_LOADING = 'WALLET_LOADING'
export const WALLET_LOAD_FAILED= 'WALLET_LOAD_FAILED'
export const SHOW_GLOBAL_HEADER= 'SHOW_GLOBAL_HEADER'
export const HIDE_GLOBAL_HEADER= 'HIDE_GLOBAL_HEADER'
export const REDIRECT = 'REDIRECT'
export const SHOW_MODAL = 'SHOW_MODAL'
export const HIDE_MODAL = 'HIDE_MODAL'
export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const REGISTER = 'REGISTER'
export const WALLET_LOAD = 'WALLET_LOAD'
export const WALLET_TRANSACTIONS_LOAD = 'WALLET_TRANSACTIONS_LOAD'
export const GAMES_LOAD = 'GAMES_LOAD'
export const GAME_CATEGORY_SELECTED = 'GAME_CATEGORY_SELECTED'
export const GAME_STARTED = 'GAME_STARTED'
export const GAME_UNLOADED = 'GAME_UNLOADED'
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'
export const GAME_QUESTION_FETCHED = 'GAME_QUESTION_FETCHED'
export const GAME_ENDED = 'GAME_ENDED'
export const GAME_RESTARTED= 'GAME_RESTARTED'
export const RELOAD_APP = 'RELOAD_APP'
export const PAYMENT_MADE = 'PAYMENT_MADE'
export const RESET_PASSWORD = 'RESET_PASSWORD'
export const TOGGLE_MENU = 'TOGGLE_MENU'
export const HIDE_GAME_SUMMARY_HEADER = 'HIDE_GAME_SUMMARY_HEADER'
export const SHOW_GAME_SUMMARY_HEADER = 'SHOW_GAME_SUMMARY_HEADER'
export const SHOW_HEADER = 'SHOW_HEADER'
export const HIDE_HEADER = 'HIDE_HEADER'
export const RANK_LOADED = 'RANK_LOADED'
export const IS_MOBILE = 'IS_MOBILE'
export const MOBILE_WIDTH = 480

export const LEADERS_LOADED = 'LEADERS_LOADED'
export const LEADERS_LOADING = 'LEADERS_LOADING'
export const LEADERS_LOADING_FAILED = 'LEADERS_LOADING_FAILED'

export const BANKS_LOADED = 'BANKS_LOADED'

export const LOAD_PROFILE = 'LOAD_PROFILE'
export const UPDATING_PROFILE = 'UPDATING_PROFILE'
export const PROFILE_UPDATED = 'PROFILE_UPDATED'
export const UPDATING_PROFILE_FAILED = 'UPDATING_PROFILE_FAILED'

export const UPLOADING_AVATAR = 'UPLOADING_AVATAR'
export const AVATAR_UPLAODED = 'AVATAR_UPLAODED'
export const AVATAR_UPLAOD_FAILED = 'AVATAR_UPLAOD_FAILED'


export const PLANS_LOADED = 'PLANS_LOADED'
export const GAME_PLAN_SELECTED = 'GAME_PLAN_SELECTED'
export const PLAN_PURCHASED = 'PLAN_PURCHASED'
export const PURCHASING_PLAN = 'PURCHASING_PLAN'
export const PURCHASING_PLAN_FAILED = 'PURCHASING_PLAN_FAILED'

//customer actions
export const CREATE_CUSTOMER = 'CREATE_CUSTOMER';
export const EDIT_CUSTOMER = 'EDIT_CUSTOMER';
export const VIEW_CUSTOMER = 'VIEW_CUSTOMER';


//user actions
export const CREATE_USER = 'CREATE_USER';
export const EDIT_USER = 'EDIT_USER';
export const VIEW_USER = 'VIEW_USER';

//global model
export const MODEL_CREATION_FAILED = 'MODEL_CREATION_FAILED';

// export const 